### ISSUE TITLE
Launcher fails to launch correctly and is unusuable

### ISSUE THREAD

**Issue by grimmspector** [Aurora-Modders/AuroraLoader#69]
**Describe the bug**

**To Reproduce**
1. Launch the loader
2. Receive error shown below
3. Launcher does not work

**Expected behavior**
The launcher should work.

**Screenshots**
![image](https://github.com/Aurora-Modders/AuroraLoader/assets/65185497/59a79772-d55f-49dc-84ab-73a1aa81a74f)

**Environment (please complete the following information):**
 - OS: Windows 10
 - AuroraLoader version [e.g. 0.22.1]: Doesn't show (see image)
 - Aurora version [e.g. 1.8.0]:  2.5.1
- Installed/selected mods and versions: Can't select anything

**Additional context**

Error given:
`************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at AuroraLoader.FormMain.RefreshAuroraInstallData()
   at AuroraLoader.FormMain.FormMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

`

**Comment by dmitrijnaprimer** [comment]
Take a closer look at the "REQUIREMENTS" field - you need to install .NET Core 3.1 Desktop Runtime. Problem solved.

Have a nice day!

**Comment by Our0b0r05** [comment]
I also have this exact same issue. I uninstalled all of my .NET Cores and installed the provided 3.1 runtime and the issue still isn't fixed.
