### ISSUE TITLE
Launcher Currently Unusable as its Unable to Download Updated AuroraLoader exe file

### ISSUE THREAD

**Issue by Emmyg2003** [Aurora-Modders/AuroraLoader#70]
**Describe the bug**
I have installed the .NET core, let Aurora Loader and the .bat file through my firewall, run as administrator all to no avail. The log just says the mirror link its trying to download the new AuroraLoader Exe from does not exist and 404's out which after following the link is true.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at AuroraLoader.FormMain.RefreshAuroraInstallData()
   at AuroraLoader.FormMain.FormMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   
   Identified checksum kWt0gg
Running Aurora 2.5.1
Updating mod registry, updateRemote=True updateCache=False
Loading local mod from C:\Users\bgiam\OneDrive\Desktop\Aurora4x\AuroraLoader\Mods\AuroraLoader\mod.json
Failed to download mod locations from https://raw.githubusercontent.com/Aurora-Modders/AuroraLoader/master/AuroraLoader/mod_locations.json
The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at AuroraLoader.Registry.ModRegistry.GetModsAtMirror(String mirrorUrl)
   at AuroraLoader.Registry.ModRegistry.GetModsFromMirrors()
Loading Aurora versions from C:\Users\bgiam\OneDrive\Desktop\Aurora4x\AuroraLoader\aurora_versions.ini
Identified checksum kWt0gg
Running Aurora 2.5.1

**To Reproduce**
1. Launch Exe
2. Error pops up
3. Press Continue
4. Spins forever and is unusable

**Expected behavior**
Launches properly

**Environment (please complete the following information):**
 - OS: **Must be Windows** Windows 11
 - AuroraLoader version [e.g. 0.22.1]: 0.23.5
 - Aurora version [e.g. 1.8.0]: 2.5.1
- Installed/selected mods and versions:

**Additional context**

**Comment by bbuske** [comment]
Same issue here
